version: '2'
services:
  php-fpm:
    build: .docker/php-fpm
    volumes_from:
      - source
    volumes:
      - ~/.ssh:/root/.ssh:rw
      - ~/.ssh:/var/www/.ssh:rw
    links:
      - mysql
      - mail
      - elasticsearch
      #- elastic${DOCKER_PROJECT_PREFIX}new
    container_name: ${DOCKER_PROJECT_PREFIX}php
    networks:
          - bitrix
    restart: always
  nginx:
        build: ./.docker/nginx
        container_name: ${DOCKER_PROJECT_PREFIX}nginx
        depends_on:
            - source
        volumes_from:
            - source
        ports:
            - '${INTERFACE}:${DOCKER_NGINX_PORT}:80'
        links:
            - php-fpm
        networks:
            bitrix:
               ipv4_address: ${DOCKER_NETWORK_IP}
        restart: always
  mysql:
        build: ./.docker/mysql
        container_name: ${DOCKER_PROJECT_PREFIX}mysql
        volumes_from:
            - source
        ports:
            - '${INTERFACE}:${DOCKER_MYSQL_PORT}:3307'
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        networks:
            - bitrix
        restart: always
  mail:
    image: mailhog/mailhog
    container_name: ${DOCKER_PROJECT_PREFIX}mail
    ports:
        - '${INTERFACE}:${DOCKER_MAIL_PORT}:8025'
    networks:
        - bitrix

  elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
        environment:
            - bootstrap.memory_lock=true
            - discovery.type=single-node
            - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
        ulimits:
            memlock:
                soft: -1
                hard: -1
        container_name: ${DOCKER_PROJECT_PREFIX}elasticsearch
        ports:
          - '${INTERFACE}:${DOCKER_ELASTICSEARCH_PORT_1}:9201'
          - '${INTERFACE}:${DOCKER_ELASTICSEARCH_PORT_2}:9301'
        networks:
            - bitrix
  source:
        image: alpine:latest
        container_name: ${DOCKER_PROJECT_PREFIX}source
        volumes:
            - ./.docker/logs/nginx:/var/log/nginx
            - ./.docker/logs/php:/var/log/php
            - ./.docker/logs/mysql:/var/log/mysql
            - ./.docker/data/mysql:/var/lib/mysql
            - .:/var/www:rw
            - ./.docker/logs/elasticsearch:/var/log/elasticsearch
        networks:
            - bitrix
networks:
    bitrix:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${DOCKER_NETWORK_SUBNET}
