---
swagger: '2.0'
info:
  title: SEARCH REST API
  description: Описание методов сервиса
  version: 1.0.0
schemes:
  - http
basePath: "/search"
produces:
  - application/json

paths:
  "/subscribe/add":
    post:
      summary: Добавление адреса в список подписчиков
      description: Добавление адреса в список подписчиков
      parameters:
        - in: body
          name: request
          required: true
          description: Параметры
          schema:
            type: object
            properties:
              email:
                description: Адрес электронной почты
                type: string
                example: test@test.com
      tags:
        - Subscription
      responses:
        '200':
          schema:
            type: array
            properties:
              success:
                type: boolean
              status:
                type: string
                example: SUBSCRIBE_SUCCESS
              data:
                type: object
                properties:
                  status:
                    type: string
                    example: SUBSCRIBE_SUCCESS
                  data:
                    type: object
                    properties:
                      result:
                        type: object
                        properties:
                          message:
                            type: string
                            example: Успешная подписка
                        description:
                    description:
                description:
            description:
          description: Метод успешно отработал
        '400':
          description: Метод отработал с ошибкой
        '404':
          description: Объет не найден
        '401':
          description: Ошибка авторизации
        '500':
          description: Внутренняя ошибка сервера

