---
swagger: '2.0'
info:
  title: Search Point REST API
  description: API для работы с фильтрацией и поиском в приложении
  version: 1.0.0
schemes:
  - http
basePath: "/search"
produces:
  - application/json

responses:
  400Error:
    description: 'Ошибочный запрос, например, отсутствует один из параметров'
    schema:
      $ref: '#/definitions/Error'
  401Error:
    description: 'Требуется аутентификация'
    schema:
      $ref: '#/definitions/Error'
  403Error:
    description: 'Недостаточно прав для выполнения запроса'
    schema:
      $ref: '#/definitions/Error'
  404Error:
    description: 'Запрашиваемый ресурс, определяемый идентификатором, не найден'
    schema:
      $ref: '#/definitions/Error'
  409Error:
    description: 'Ресурс, создаваемый методом POST, уже существует'
    schema:
      $ref: '#/definitions/Error'
  500Error:
    description: 'Серверная ошибка'
    schema:
      $ref: '#/definitions/Error'

paths:
  "/catalog/list/":
    get:
      summary: Получение списка элементов
      description: Получение списка элементов
      parameters:
        - in: body
          name: catalogListFilter
          required: true
          schema:
            $ref: '#/definitions/catalogListFilter'
      tags:
      - Catalog
      responses:
        200:
          description: Метод успешно отработал
          schema:
          uniqueItems: false
          type: array
          items:
            $ref: '#/definitions/listItem'
        400:
          $ref: '#/responses/400Error'
        403:
          $ref: '#/responses/403Error'
        404:
          $ref: '#/responses/404Error'
        500:
          $ref: '#/responses/500Error'

  "/catalog/filter/":
    get:
      summary: Возвращает варианты значений для параметров фильтра
      description: Возвращает варианты значений для параметров фильтра
      parameters:
      - in: body
        name: request
        required: true
        description: Параметры
        schema:
          type: object
          properties:
            sectionId:
              description: ID раздела
              type: integer
              example: 3026
            query:
              description: Поисковый запрос
              type: string
              example: обувь
            filter:
              description: Описание параметров и установленных значений
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                    values:
                      type: array
              example: [{"id": "93", "values": ["41","42","XXL"]}, {"id": "94", "values": ["white"]}, {"id": "price_base", "values": {"min": "50", "max": "5000"}}]
      tags:
      - Catalog
      responses:
        '200':
          description: Метод успешно отработал
        '400':
          description: Метод отработал с ошибкой
        '404':
          description: Объет не найден
        '401':
          description: Ошибка авторизации
        '500':
          description: Внутренняя ошибка сервера

  "/search/suggests/":
    get:
      summary: Возвращает поисковые подсказки
      description: Возвращает поисковые подсказки/предложения по товарам и товарным группам
      parameters:
      - in: body
        name: request
        required: true
        description: Параметры
        schema:
          type: object
          properties:
            query:
              description: Поисковый запрос
              type: string
              example: Футболка
            limits:
              description: Ограничесние выборки
              type: object
              properties:
                products:
                  type: integer
                  example: 5
                categories:
                  type: integer
                  example: 4
      tags:
      - Search
      responses:
        '200':
          description: Метод успешно отработал
        '400':
          description: Метод отработал с ошибкой
        '404':
          description: Объет не найден
        '401':
          description: Ошибка авторизации
        '500':
          description: Внутренняя ошибка сервера

  "/search/filter/":
    get:
      summary: Возвращает варианты значений для параметров фильтра
      description: Возвращает варианты значений для параметров фильтра
      parameters:
      - in: body
        name: request
        required: true
        description: Параметры
        schema:
          type: object
          properties:
            sectionId:
              description: ID раздела
              type: integer
              example: 3026
            query:
              description: Поисковый запрос
              type: string
              example: обувь
            filter:
              description: Описание параметров и установленных значений
              type: array
              items:
                type: object
                properties:
                  id:
                    type: string
                    values:
                      type: array
              example: [{"id": "93", "values": ["41","42","XXL"]}, {"id": "94", "values": ["white"]}, {"id": "price_base", "values": {"min": "50", "max": "5000"}}]
      tags:
      - Search
      responses:
        '200':
          description: Метод успешно отработал
        '400':
          description: Метод отработал с ошибкой
        '404':
          description: Объет не найден
        '401':
          description: Ошибка авторизации
        '500':
          description: Внутренняя ошибка сервера

  "/search/list/":
    get:
      summary: Получение списка элементов
      description: Получение списка товаров на основе поискового запроса и фильтрации
      parameters:
      - in: body
        name: request
        required: true
        description: Параметры
        schema:
          type: object
          properties:
            sortField:
              description: поле для сортировки price, SORT
              type: string
              example: "SORT"
            sortOrder:
              description: направление сортировки desc, asc
              type: string
              example: "asc"
            pageSize:
              description: количество товаров на странице
              type: integer
              example: 15
            filterUrl:
              description: строка фильтрации
              type: string
              example: "футболка/filter/brand-is-lacoste/apply/"
            num:
              description: номер страницы, которую нужно вернуть
              type: integer
              example: 1
      tags:
      - Search
      responses:
        '200':
          description: Метод успешно отработал
        '400':
          description: Метод отработал с ошибкой
        '404':
          description: Объет не найден
        '401':
          description: Ошибка авторизации
        '500':
          description: Внутренняя ошибка сервера

definitions:
  catalogListFilter:
    type: object
    description: Объект фильтрации
    properties:
      params:
        type: object
        properties:
          rangeParams:
            type: array
            description: |
              Массив параметров фильтра типа range
            items:
              $ref: '#/definitions/catalogListFilterRangeParam'

          selectParams:
            type: array
            description: |
              Массив параметров фильтра остальных типов (checkbox, radio, select)
            items:
              $ref: '#/definitions/catalogListFilterParam'


  catalogListFilterRangeParam:
    type: object
    required:
      - type
      - code
      - values
    properties:
      code:
        type: string
        description: |
          Символьный код параметра
        example: "rent_price"
      sort:
        type: integer
        description: |
          Индекс сортировки параметра
        example: 500
      name:
        type: string
        description: |
          Название параметра
        example: 'Стоимость аренды'
      description:
        type: string
        description: |
          Описание параметра
        example: 'Произвольное описание параметра'
      img:
        type: string
        description: |
          Картинка для параметра
        example: 'https://cdn.fast.ru/files/1sdasd88dasdsad.jpg'
      additional_info:
        type: string
        description: |
          Дополнительная информация для параметра
        example: 'string'
      disabled:
        type: boolean
        description: |
          Значение недоступно для выбора
        example: true
      unit:
        type: string
        description: |
          Единица измерения значения свойства
        example: 'руб.'
      minValue:
        type: number
        description: |
          Минимальное значение свойства
        example: 1500
      maxValue:
        type: number
        description: |
          Максимальное значение свойства
        example: 10000
      minSelectedValue:
        type: number
        description: |
          Минимальное выбранное значение свойства
        example: 3000
      maxSelectedValue:
        type: number
        description: |
          Максимальное выбранное значение свойства
        example: 7000

  catalogListFilterParam:
    type: object
    required:
      - type
      - code
      - values
    properties:
      type:
        type: string
        enum: [checkbox, radio, select]
        description: |
          Тип параметра
        example: "checkbox"
      code:
        type: string
        description: |
          Символьный код параметра
        example: "color"
      sort:
        type: integer
        description: |
          Индекс сортировки параметра
        example: 500
      name:
        type: string
        description: |
          Название значения параметра
        example: 'Цвет'
      description:
        type: string
        description: |
          Описание параметра
        example: 'Произвольное описание параметра'
      img:
        type: string
        description: |
          Картинка для параметра
        example: 'https://cdn.fast.ru/files/1sdasd88dasdsad.jpg'
      additional_info:
        type: string
        description: |
          Дополнительная информация для параметра
        example: 'string'
      values:
        type: array
        description: |
          Массив значений параметра
        items:
          $ref: '#/definitions/catalogListFilterValue'

  catalogListFilterValue:
    type: object
    required:
      - count
      - checked
      - disabled
    properties:
      count:
        type: integer
        description: |
          Количество элементов, удовлетворяющих значению
        example: 5
      checked:
        type: boolean
        description: |
          Значение параметра выбрано
        example: true
      disabled:
        type: boolean
        description: |
          Значение недоступно для выбора
        example: true
      sort:
        type: integer
        description: |
          Индекс сортировки значения
        example: 500
      name:
        type: string
        description: |
          Название значения свойства
        example: 'Красный'
      description:
        type: string
        description: |
          Описание значения параметра
        example: 'Произвольное описание параметра'
      img:
        type: string
        description: |
          Картинка для значения параметра
        example: 'https://cdn.fast.ru/files/1sdasd88dasdsad.jpg'
      additional_info:
        type: string
        description: |
          Дополнительная информация для значения параметра
        example: 'string'
      value:
        type: string
        description: |
          Значение свойства
        example: 'red'

  listItem:
    type: object
    required:
      - id
      - attributes
    properties:
      id:
        type: string
        description: |
          Идентификатор элемента
        example: 5
      attributes:
        type: object
        properties:
          single:
            type: array
            description: |
              Массив одиночных свойств элемента
            items:
              $ref: '#/definitions/listItemSingleAttribute'
          multiple:
            type: array
            description: |
              Массив множественных свойств элемента
            items:
              $ref: '#/definitions/listItemMultipleAttribute'

  listItemSingleAttribute:
    type: object
    properties:
      id:
        type: string
        description: |
          Идентификатор аттрибута элемента
        example: 764
      name:
        type: string
        description: |
          Название аттрибута
        example: 'Тип коробки передач'
      description:
        type: string
        description: |
          Описание аттрибута
        example: 'Произвольное описание параметра'
      img:
        type: string
        description: |
          Картинка для аттрибута
        example: 'https://cdn.fast.ru/files/1sdasd88dasdsad.jpg'
      additional_info:
        type: string
        description: |
          Дополнительная информация для значения аттрибута
        example: 'string'
      value:
        $ref: '#/definitions/listItemAttributeValue'

  listItemMultipleAttribute:
      type: object
      properties:
        id:
          type: string
          description: |
            Идентификатор аттрибута элемента
          example: 764
        name:
          type: string
          description: |
            Название аттрибута
          example: 'Тип коробки передач'
        description:
          type: string
          description: |
            Описание аттрибута
          example: 'Произвольное описание параметра'
        img:
          type: string
          description: |
            Картинка для аттрибута
          example: 'https://cdn.fast.ru/files/1sdasd88dasdsad.jpg'
        additional_info:
          type: string
          description: |
            Дополнительная информация для значения аттрибута
          example: 'string'
        values:
          type: array
          description: |
            Массив значений аттрибута
          items:
            $ref: '#/definitions/listItemAttributeValue'

  listItemAttributeValue:
      type: object
      properties:
        id:
          type: string
          description: |
            Идентификатор значения аттрибута элемента
          example: 44
        description:
          type: string
          description: |
            Описание значения аттрибута
          example: 'Произвольное описание параметра'
        img:
          type: string
          description: |
            Картинка для значения аттрибута
          example: 'https://cdn.fast.ru/files/1sdasd88dasdsad.jpg'
        additional_info:
          type: string
          description: |
            Дополнительная информация для значения аттрибута
          example: 'string'
        value:
          type: string
          description: |
            Значение аттрибута
          example: 'АКПП'

  Error:
    description: Описание ошибки для всех методов
    properties:
      applicationErrorCode:
        description: |
          Код ошибки, к которому привел вызов метода
        type: string
        example: 'tooManyRequests'
      debug:
        description: |
          Дополнительная отладочная информация
        type: string
        example: 'org.postgresql.util.PSQLException: ERROR: canceling statement due to user request'
      message:
        description: |
          Человекочитаемое сообщение об ошибке
        type: string
        example: 'Ошибка отправки СМС-сообщения'
    required:
      - applicationErrorCode
      - message
